logging:
  level:
    com.hzx.blog: debug
  file:
    name: ./log/prod/blog_prod.log
server:
  port: 80
spring:
#  配置Redis
  redis:
    port: 6379
    host: 127.0.0.1 #这里用的是阿里云的服务器
#  配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/new_blog?serverTimezone=UTC
    username: root
    password: root